steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "Listing contents of /workspace:"
      ls -la /workspace  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'flask-cloudbuild-app',
      '--image', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
   - name: 'gcr.io/cloud-builders/gcloud'
     args: ['app', 'deploy', '--quiet']

images:
  - 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app'

logsBucket: 'gs://mybucket579'
