steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'flaskapi/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/flask-cloudbuild-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-cloudbuild-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'flask-cloudbuild-app',
      '--image', 'gcr.io/$PROJECT_ID/flask-cloudbuild-app',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/flask-cloudbuild-app'

logsBucket: 'gs://mybucket579'
