steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing contents of /workspace:"
        ls -la /workspace

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-cloudbuild-app'
      - '--image=us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s/IMAGE_TAG/$COMMIT_SHA/" k8s/deployment.yaml > k8s/deployment-final.yaml
        kubectl apply -f k8s/deployment-final.yaml

images:
  - 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app:$COMMIT_SHA'

logsBucket: 'gs://mybucket579'
